name = "hangmanml"
type = "javascript"
zone_id = ""
account_id = "5b2b0b87a1b375359c944abef425ae5e"
route = "*"
workers_dev = true
compatibility_date = "2021-11-21"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
